### ISSUE TITLE
Enhance colors and add text on gif image

### ISSUE THREAD

**Issue by kenorb** [EA31337/FX-MT-VM#58]
The goal is to replace existing colors and add custom text into the given gif image.

### Testing:

1. Place the [gif image](https://github.com/EA31337/EA31337-Lite-Sets/blob/master/EURUSD/spread-10/digits-5/2014/EURUSD-2000USD-2014year-10spread-DS-main-test.gif) into the cloned repository.
1. Run: `./scripts/eval.sh enhance_gif *.gif`

The enhanced image should be modified as described below.

### Tasks

Extend `enhance_gif()` from `scripts/.initrc` (dev branch) in order to:

- [x] - negate the image (this is already done)
- [x] - replace pink with blue, yellow with green
- [x] - add 3 lines of custom static text (later to be changed) below Balance/Equity line (ideally with similar font), e.g.

        Symbol                    EURUSD (Euro vs US Dollar)
        Model                     Every tick (the most precise method based on all available least timeframes)
        Bars in test       368715 Ticks modelled               74312557 Modelling quality                 24.99%

Est. 2-3h

**Comment by lu43n** [comment]
Done: 2h

**Comment by kenorb** [comment]
Fixed in #63
